core/urls.py
from core.views.index import IndexTemplateView
from core.views.profile import update_profile

from django.urls import path


app_name = 'core'

urlpatterns = [


    path('', IndexTemplateView.as_view(), name="index"),
    
    path('profile', update_profile, name='updateprofile'),



 ]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.urls.conf import include

urlpatterns = [
    path('', include('core.urls', namespace='core')),


    path('admin/', admin.site.urls),
]

core/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

core/forms/profileform.py
from django.contrib.auth.models import User
from core.models import Profile
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date')

core/views.py
from django.shortcuts import render

from django.views.generic import TemplateView
# Create your views here.


class IndexTemplateView(TemplateView):
    template_name = "core/index.html"

core/views/index.py
from django.shortcuts import render

from django.views.generic import TemplateView
# Create your views here.


class IndexTemplateView(TemplateView):
    template_name = "core/index.html"

core/views/profile.py
from core.forms.profileform import UserForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect
from django.contrib import messages

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('core:updateprofile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'core/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

core/templates/core/index.html
<!-- Estendemos do template base -->
{% comment %} {% extends "core/_layouts/base.html" %} {% endcomment %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}

<div class="container mt-5">
<h2><a href="{% url 'core:index' %}">Inicio</a></h2>
</br>
	<p class="mb-3">{% lorem %}</p>
	<p class="mb-3">{% lorem %}</p>
	<p class="mb-3">{% lorem %}</p>
	<p class="mb-3">{% lorem %}</p>

 </div>
{% endblock %}

core/templates/core/profile.html
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Save changes</button>
  </form>

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}